### ISSUE TITLE
context API warnings in React

### ISSUE THREAD

**Issue by zarinda** [willb335/chessboardjsx#58]
Please update the following components: DragDropContext(t), DragLayer(t)

Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: DragDropContext(t), DragLayer(t)

Learn more about this warning here: https://reactjs.org/link/legacy-context
    at DragDropContext(t) (http://localhost:3000/static/js/0.chunk.js:2540:14)
    at Route (http://localhost:3000/static/js/0.chunk.js:44273:29)
    at Switch (http://localhost:3000/static/js/0.chunk.js:44475:29)
    at div
    at Content
    at Router (http://localhost:3000/static/js/0.chunk.js:43908:30)
    at BrowserRouter (http://localhost:3000/static/js/0.chunk.js:43528:35)
    at div
    at App

**Comment by willb335** [comment]
This library is no longer maintained.  There are other, more stable, chessboard libraries that could fit your use case

**Comment by zarinda** [comment]
> This library is no longer maintained. There are other, more stable, chessboard libraries that could fit your use case

Would you please give me the links? chessboard libraries

**Comment by willb335** [comment]
https://github.com/ruilisi/react-chessground
